DEBUG 2019-07-05 00:03:35,970: 	 Executing command: 'submit'
DEBUG 2019-07-05 00:03:35,970: 	 Found CRAB cache file /afs/cern.ch/user/x/xuyan/.crab3
DEBUG 2019-07-05 00:03:35,982: 	 Checking credentials
DEBUG 2019-07-05 00:03:35,983: 	 Found proxy file /tmp/x509up_u93529
DEBUG 2019-07-05 00:03:35,983: 	 Getting proxy life time left
DEBUG 2019-07-05 00:03:36,893: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -timeleft
 output : 43193

 error: 
 retcode : 0
DEBUG 2019-07-05 00:03:38,111: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -actimeleft
 output : 43191

 error: 
 retcode : 0
DEBUG 2019-07-05 00:03:38,111: 	 Proxy lifetime 43193 secs is different from voms extension lifetime 43191 secs for proxy: /tmp/x509up_u93529
DEBUG 2019-07-05 00:03:38,111: 	 Proxy valid for 11:59:51 hours
INFO 2019-07-05 00:03:38,111: 	 Will use CRAB configuration file crabconfigs/crab_Signal.py
DEBUG 2019-07-05 00:03:38,112: 	 Loading CRAB configuration file.
DEBUG 2019-07-05 00:03:41,595: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-07-05 00:03:41,596: 	 Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul04/crab_Wgamma949SignalFinal_v2_Jul04' already exists 
Please change the requestName in the config file
ERROR 2019-07-05 00:03:41,596: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul04/crab_Wgamma949SignalFinal_v2_Jul04' already exists 
Please change the requestName in the config file
DEBUG 2019-07-05 14:43:26,928: 	 Executing command: 'submit'
DEBUG 2019-07-05 14:43:26,933: 	 Found CRAB cache file /afs/cern.ch/user/x/xuyan/.crab3
DEBUG 2019-07-05 14:43:26,976: 	 Checking credentials
DEBUG 2019-07-05 14:43:26,977: 	 Found proxy file /tmp/x509up_u93529
DEBUG 2019-07-05 14:43:26,977: 	 Getting proxy life time left
ERROR 2019-07-05 14:43:27,387: 	 Keyboard Interrupted
