DEBUG 2019-08-14 11:44:32,072: 	 Executing command: 'status'
DEBUG 2019-08-14 11:44:32,072: 	 Found CRAB cache file /afs/cern.ch/user/x/xuyan/.crab3
ERROR 2019-08-14 11:44:32,073: 	 Error: /afs/cern.ch/work/x/xuyan/work5/PROD17/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_2017F_photonAug14/crab_Wgamma94XSinglePhoton_Aug14_2017F is not a valid CRAB project directory.
ERROR 2019-08-14 11:44:32,073: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 586, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: /afs/cern.ch/work/x/xuyan/work5/PROD17/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_2017F_photonAug14/crab_Wgamma94XSinglePhoton_Aug14_2017F is not a valid CRAB project directory.
DEBUG 2019-08-14 11:52:18,529: 	 Executing command: 'submit'
DEBUG 2019-08-14 11:52:18,529: 	 Found CRAB cache file /afs/cern.ch/user/x/xuyan/.crab3
DEBUG 2019-08-14 11:52:18,550: 	 Checking credentials
DEBUG 2019-08-14 11:52:18,551: 	 Found proxy file /tmp/x509up_u93529
DEBUG 2019-08-14 11:52:18,551: 	 Getting proxy life time left
ERROR 2019-08-14 11:52:18,692: 	 Keyboard Interrupted
