DEBUG 2019-07-05 00:03:35,970: 	 Executing command: 'submit'
DEBUG 2019-07-05 00:03:35,970: 	 Found CRAB cache file /afs/cern.ch/user/x/xuyan/.crab3
DEBUG 2019-07-05 00:03:35,982: 	 Checking credentials
DEBUG 2019-07-05 00:03:35,983: 	 Found proxy file /tmp/x509up_u93529
DEBUG 2019-07-05 00:03:35,983: 	 Getting proxy life time left
DEBUG 2019-07-05 00:03:36,893: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -timeleft
 output : 43193

 error: 
 retcode : 0
DEBUG 2019-07-05 00:03:38,111: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -actimeleft
 output : 43191

 error: 
 retcode : 0
DEBUG 2019-07-05 00:03:38,111: 	 Proxy lifetime 43193 secs is different from voms extension lifetime 43191 secs for proxy: /tmp/x509up_u93529
DEBUG 2019-07-05 00:03:38,111: 	 Proxy valid for 11:59:51 hours
INFO 2019-07-05 00:03:38,111: 	 Will use CRAB configuration file crabconfigs/crab_Signal.py
DEBUG 2019-07-05 00:03:38,112: 	 Loading CRAB configuration file.
DEBUG 2019-07-05 00:03:41,595: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-07-05 00:03:41,596: 	 Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul04/crab_Wgamma949SignalFinal_v2_Jul04' already exists 
Please change the requestName in the config file
ERROR 2019-07-05 00:03:41,596: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul04/crab_Wgamma949SignalFinal_v2_Jul04' already exists 
Please change the requestName in the config file
DEBUG 2019-07-05 14:43:26,928: 	 Executing command: 'submit'
DEBUG 2019-07-05 14:43:26,933: 	 Found CRAB cache file /afs/cern.ch/user/x/xuyan/.crab3
DEBUG 2019-07-05 14:43:26,976: 	 Checking credentials
DEBUG 2019-07-05 14:43:26,977: 	 Found proxy file /tmp/x509up_u93529
DEBUG 2019-07-05 14:43:26,977: 	 Getting proxy life time left
ERROR 2019-07-05 14:43:27,387: 	 Keyboard Interrupted
DEBUG 2019-07-10 15:20:21,127: 	 Executing command: 'submit'
DEBUG 2019-07-10 15:20:21,129: 	 Found CRAB cache file /afs/cern.ch/user/x/xuyan/.crab3
DEBUG 2019-07-10 15:20:21,174: 	 Checking credentials
DEBUG 2019-07-10 15:20:21,176: 	 Found proxy file /tmp/x509up_u93529
DEBUG 2019-07-10 15:20:21,176: 	 Getting proxy life time left
DEBUG 2019-07-10 15:20:22,283: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -timeleft
 output : 42666

 error: 
 retcode : 0
DEBUG 2019-07-10 15:20:23,192: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -actimeleft
 output : 42665

 error: 
 retcode : 0
DEBUG 2019-07-10 15:20:23,192: 	 Proxy lifetime 42666 secs is different from voms extension lifetime 42665 secs for proxy: /tmp/x509up_u93529
DEBUG 2019-07-10 15:20:23,192: 	 Proxy valid for 11:51:05 hours
INFO 2019-07-10 15:20:23,196: 	 Will use CRAB configuration file crabconfigs/crab_Signal.py
DEBUG 2019-07-10 15:20:23,196: 	 Loading CRAB configuration file.
DEBUG 2019-07-10 15:20:26,587: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-07-10 15:20:26,588: 	 Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul10/crab_Wgamma949SignalFinal_Jul10' already exists 
Please change the requestName in the config file
ERROR 2019-07-10 15:20:26,588: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul10/crab_Wgamma949SignalFinal_Jul10' already exists 
Please change the requestName in the config file
DEBUG 2019-07-10 16:16:07,864: 	 Executing command: 'submit'
DEBUG 2019-07-10 16:16:07,865: 	 Found CRAB cache file /afs/cern.ch/user/x/xuyan/.crab3
DEBUG 2019-07-10 16:16:07,971: 	 Checking credentials
DEBUG 2019-07-10 16:16:07,972: 	 Found proxy file /tmp/x509up_u93529
DEBUG 2019-07-10 16:16:07,972: 	 Getting proxy life time left
DEBUG 2019-07-10 16:16:08,980: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -timeleft
 output : 39320

 error: 
 retcode : 0
DEBUG 2019-07-10 16:16:09,795: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -actimeleft
 output : 39319

 error: 
 retcode : 0
DEBUG 2019-07-10 16:16:09,795: 	 Proxy lifetime 39320 secs is different from voms extension lifetime 39319 secs for proxy: /tmp/x509up_u93529
DEBUG 2019-07-10 16:16:09,795: 	 Proxy valid for 10:55:19 hours
INFO 2019-07-10 16:16:09,800: 	 Will use CRAB configuration file crabconfigs/crab_Signal.py
DEBUG 2019-07-10 16:16:09,800: 	 Loading CRAB configuration file.
DEBUG 2019-07-10 16:16:14,207: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-07-10 16:16:14,207: 	 Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul10/crab_Wgamma949SignalFinal2000_Jul10' already exists 
Please change the requestName in the config file
ERROR 2019-07-10 16:16:14,208: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul10/crab_Wgamma949SignalFinal2000_Jul10' already exists 
Please change the requestName in the config file
DEBUG 2019-07-10 16:22:41,481: 	 Executing command: 'submit'
DEBUG 2019-07-10 16:22:41,481: 	 Found CRAB cache file /afs/cern.ch/user/x/xuyan/.crab3
DEBUG 2019-07-10 16:22:41,524: 	 Checking credentials
DEBUG 2019-07-10 16:22:41,526: 	 Found proxy file /tmp/x509up_u93529
DEBUG 2019-07-10 16:22:41,526: 	 Getting proxy life time left
DEBUG 2019-07-10 16:22:42,435: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -timeleft
 output : 38926

 error: 
 retcode : 0
DEBUG 2019-07-10 16:22:43,242: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93529 -actimeleft
 output : 38925

 error: 
 retcode : 0
DEBUG 2019-07-10 16:22:43,242: 	 Proxy lifetime 38926 secs is different from voms extension lifetime 38925 secs for proxy: /tmp/x509up_u93529
DEBUG 2019-07-10 16:22:43,242: 	 Proxy valid for 10:48:45 hours
INFO 2019-07-10 16:22:43,244: 	 Will use CRAB configuration file crabconfigs/crab_Signal.py
DEBUG 2019-07-10 16:22:43,244: 	 Loading CRAB configuration file.
DEBUG 2019-07-10 16:22:46,392: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-07-10 16:22:46,392: 	 Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul10/crab_Wgamma949SignalFinal2000_Jul10' already exists 
Please change the requestName in the config file
ERROR 2019-07-10 16:22:46,393: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/x/xuyan/work5/DEV/CMSSW_9_4_9/src/VgammaTuplizer/Ntuplizer/crab_jobs_signalJul10/crab_Wgamma949SignalFinal2000_Jul10' already exists 
Please change the requestName in the config file
